# Generated by Django 4.1.7 on 2023-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('house_address', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('martial_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Annualled', 'Annualled'), ('Widowed', 'Widowed')], max_length=100)),
                ('if_married', models.CharField(choices=[('Holy Matrimony', 'Holy Matrimony'), ('Traditional Marriage', 'Traditional Marriage'), ('None', 'None')], max_length=100)),
                ('spouse_name', models.CharField(max_length=100)),
                ('number_of_children', models.IntegerField()),
                ('children_names', models.TextField()),
                ('mother_name', models.CharField(max_length=100)),
                ('is_mother_alive', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('mother_religious_denomination', models.CharField(choices=[('Catholics', 'Catholic'), ('Other', 'Other')], max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('is_father_alive', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('father_religious_denomination', models.CharField(choices=[('Catholics', 'Catholic'), ('Other', 'Other')], max_length=100)),
                ('place_of_employment', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('baptized', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('baptized_place', models.CharField(max_length=100)),
                ('confirmed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('confirmation_place', models.CharField(max_length=100)),
                ('number_of_society', models.IntegerField()),
                ('society', models.CharField(max_length=100)),
            ],
        ),
    ]
