# Generated by Django 4.1.7 on 2023-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Welfare', 'Welfare Dues'), ('church-dues', 'Church Dues'), ('harvest-dues', 'Harvest Dues')], max_length=20),
        ),
    ]
