# Generated by Django 4.1.7 on 2023-06-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0015_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
