# Generated by Django 4.1.7 on 2023-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0016_remove_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='society',
            field=models.CharField(choices=[('Sacred Heart of Confraternity', 'Sacred Heart of Confraternity'), ('Youth Choir', 'Youth Choir'), ('Legion of Mary', 'Legion of Mary'), ('Charismatic', 'Charismatic'), ('St Theresa Society', 'St Theresa Society'), ('Cosra', 'Cosra'), ('Children of Mary', 'Children of Mary'), ('Knight of Marshall', 'Knight of Marshall'), ('Young Mens', 'Young Mens'), ('Mary Mother of Mothers', 'Mary Mother of Mothers'), ('Theresa Mma Kuo', 'Theresa Mma Kuo'), ('Mens Society', 'Mens Society'), ('Senior Choir', 'Senior Choir'), ('Lay Readers', 'Lay Readers'), ('Ushers', 'Ushers'), ('St Anthony Guild', 'St Anthony Guild'), ('Northern Union', 'Northern Union'), ('CYO', 'CYO'), ('St Theresa Guild', 'St Theresa Guild'), ('KLBS', 'KLBS'), ('Knight and Ladies of St John', 'Knight and Ladies of St John')], max_length=100),
        ),
    ]
