# Generated by Django 4.1.7 on 2023-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0018_alter_churchmember_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='children_names',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
