# Generated by Django 4.1.7 on 2023-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_alter_churchmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='profile_images'),
        ),
    ]
