# Generated by Django 4.1.7 on 2023-06-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0008_alter_churchmember_martial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmember',
            name='martial_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=100),
        ),
    ]
