# Generated by Django 4.1.7 on 2023-06-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_alter_churchmember_martial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_type', models.CharField(choices=[('welfare-dues', 'Welfare Dues'), ('church-dues', 'Church Dues'), ('harvest-dues', 'Harvest Dues')], max_length=20)),
            ],
        ),
    ]
