# Generated by Django 4.1.7 on 2023-06-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0013_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='time',
            new_name='date',
        ),
    ]
