# Generated by Django 4.1.7 on 2023-06-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0014_rename_time_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_image', models.ImageField(upload_to='document_image')),
            ],
        ),
    ]
